nelmio_api_doc:
    documentation:
        info:
            title: Mon API de blog
            description: Cette API permet de gérer les posts d'un blog
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
